# GBA 465 Lab 6 A - Skill-Building with NumPy (Starter)

## Part A - List of Lists

Let's start by working with data in the form of a list of lists.

**Action:** Execute the following code block:

In [1]:
# Stranger Things episodes per season, length in minutes:

season_1_lengths = [ 48, 55, 52, 50, 53, 47, 42, 55 ]
season_2_lengths = [ 48, 56, 51, 46, 58, 51, 45, 47 ]
season_3_lengths = [ 50, 50, 49, 52, 52, 59, 55, 77 ]

**Actions:**
- Use `season_1_lengths`, `season_2_lengths`, and `season_3_lengths` to create a list of lists.
- Store your list of lists in a variable named `episode_lengths`.

In [2]:
# Your implementation:

episode_lengths = [season_1_lengths, season_2_lengths, season_3_lengths]

**Action:** Use indexing to print the length of Season 1, Episode 6 from the list of lists `episode_lengths`.

In [3]:
# Your implementation:

print("Length of Season 1, Episode 6:", episode_lengths[0][5])

Length of Season 1, Episode 6: 47


**Action:** Use indexing to print the length of Season 2, Episode 3 from the list of lists `episode_lengths`.

In [4]:
# Your implementation:

print("Length of Season 2, Episode 3:", episode_lengths[1][2])

Length of Season 2, Episode 3: 51


## Part B - Using NumPy

**Action:** Import the NumPy packaging and use a prefix of `np`.

In [5]:
# Your implementation:

import numpy as np

**Action:** Create a NumPy array by passing the data from `episode_lengths` to the `np.array` function.

In [6]:
# Your implementation:

numpy_array = np.array(episode_lengths)

**Action:** Calculate and print the total of **all** the values in the NumPy array by using the array's `sum` method.

In [7]:
# Your implementation:

print("Total length of all episodes:", numpy_array.sum())

Total length of all episodes: 1248


## Part C - Creating and Inspecting a 1D NumPy Array

**Action:** Create a 1-dimensional (1D) array with the data from Stranger Things, Season 1 episode lengths (in minutes).

You may reference these values from `season_1_lengths`.

In [8]:
# Your implementation:

season_1_array = np.array(season_1_lengths)

**Action:** Print the NumPy array object.

In [9]:
# Your implementation:

print("Array:", season_1_array)

Array: [48 55 52 50 53 47 42 55]


**Action:** Print the **type** of the object.

In [10]:
# Your implementation:

print("Type:", type(season_1_array))

Type: <class 'numpy.ndarray'>


**Action:** Print the **length** of the array.

In [11]:
# Your implementation:

print("Length:", len(season_1_array))

Length: 8


**Action:** Print the size of the array (the total number of elements).

In [12]:
# Your implementation:

print("Size:", season_1_array.size)


Size: 8


**Action:** Print  the **shape** of the array (the description of the data's dimensions).

In [13]:
# Your implementation:

print("Shape:", season_1_array.shape)

Shape: (8,)


## Part D - Creation and Inspection a 2D NumPy Array

**Actions:**

- Create a 2-dimensional (2D) array with the data from Stranger Things, Season 1, 2, and 3 episode lengths (in minutes).
- For the argument, you can use either:
    - `episode_lengths`, or
    - `season_1_lengths` with `season_2_lengths` and `season_2_lengths`.
- Store the NumPy array object in a variable called `my_2d_array`.

In [14]:
# Your implementation:

my_2d_array = np.array(episode_lengths)

**Action:** Inspect the 2D NumPy array object:
1. Print the object itself
2. Print the type of the object
3. Print the length of the object
4. Print the size of the object
5. Print the shape of the object

In [15]:
# Your implementation:

print("Array:")
print(my_2d_array)
print("Type:", type(my_2d_array))
print("Length:", len(my_2d_array))
print("Size:", my_2d_array.size)
print("Shape:", my_2d_array.shape)

Array:
[[48 55 52 50 53 47 42 55]
 [48 56 51 46 58 51 45 47]
 [50 50 49 52 52 59 55 77]]
Type: <class 'numpy.ndarray'>
Length: 3
Size: 24
Shape: (3, 8)


## Part E - Re-Creating a 2D NumPy Array with a Data Type Constraint

**Actions:**
- Re-create the 2D NumPy array object again - but this time, use the optional parameter of `np.array` to constrain the values to an **integer**.
- Store the NumPy array object in a variable called `my_2d_array`.

In [16]:
# Your implementation:

my_2d_array = np.array(episode_lengths, dtype=int)


**Action:** As an inspection, print the data type of the object.

In [17]:
# Your implementation:

print("Data type:", my_2d_array.dtype)

Data type: int64


## Part F - Converting One Data Type to Another

**Action:** Use the `astype` method to convert values in `my_2d_array` to floats and print the results.

In [18]:
# Your implementation:
float_array = my_2d_array.astype(float)
print("Converted to float:\n", float_array)


Converted to float:
 [[48. 55. 52. 50. 53. 47. 42. 55.]
 [48. 56. 51. 46. 58. 51. 45. 47.]
 [50. 50. 49. 52. 52. 59. 55. 77.]]


**Action:** Do the same conversion as above, but this time copy the array to a new variable.  Print the new array.

You can use either the copy method (of the array object) or the copy function (of the NumPy package).

In [19]:
# Your implementation
new_array = my_2d_array.copy()
print("Copied array:\n", new_array)


Copied array:
 [[48 55 52 50 53 47 42 55]
 [48 56 51 46 58 51 45 47]
 [50 50 49 52 52 59 55 77]]


**Action:** Convert the values in `my_2d_array` to strings and print.

In [20]:
# Your implementation:
str_array = my_2d_array.astype(str)
print("Converted to string:\n", str_array)


Converted to string:
 [['48' '55' '52' '50' '53' '47' '42' '55']
 ['48' '56' '51' '46' '58' '51' '45' '47']
 ['50' '50' '49' '52' '52' '59' '55' '77']]


**Action:** Convert the values in `my_2d_array` to Booleans and print.

In [21]:
# Your implementation:
bool_array = my_2d_array.astype(bool)
print("Converted to boolean:\n", bool_array)

Converted to boolean:
 [[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


## Part G - Aggregate Methods

### Sum
**Action:** Determine the sum of all the items in `my_2d_array`.

In [22]:
# Your implementation:
print("Sum of all items:", my_2d_array.sum())


Sum of all items: 1248


**Action:** Calculate the sum for each column in `my_2d_array`.

In [23]:
# Your implementation:
print("Sum of each column:", my_2d_array.sum(axis=0))


Sum of each column: [146 161 152 148 163 157 142 179]


**Action:** Calculate the sum for each row in `my_2d_array`.

In [24]:
# Your implementation:
print("Sum of each row:", my_2d_array.sum(axis=1))


Sum of each row: [402 402 444]


### Minimum
**Action:** Determine the minimum value of all the items in `my_2d_array`.

In [25]:
# Your implementation:
print("Minimum value of all items:", my_2d_array.min())


Minimum value of all items: 42


**Action:** Calculate the minimum value for each column in `my_2d_array`.

In [26]:
# Your implementation:
print("Minimum value of each column:", my_2d_array.min(axis=0))


Minimum value of each column: [48 50 49 46 52 47 42 47]


**Action:** Calculate the minimum value for each row in `my_2d_array`.

In [27]:
# Your implementation:
print("Minimum value of each row:", my_2d_array.min(axis=1))


Minimum value of each row: [42 45 49]


### Maximum
**Action:** Determine the maximum value of all the items in `my_2d_array`.

In [28]:
# Your implementation:
print("Maximum value of all items:", my_2d_array.max())


Maximum value of all items: 77


**Action:** Calculate the maximum value for each column in `my_2d_array`.

In [29]:
# Your implementation:
print("Maximum value of each column:", my_2d_array.max(axis=0))


Maximum value of each column: [50 56 52 52 58 59 55 77]


**Action:** Calculate the maximum value for each row in `my_2d_array`.

In [30]:
# Your implementation:
print("Maximum value of each row:", my_2d_array.max(axis=1))


Maximum value of each row: [55 58 77]


### Mean
**Action:** Calculate the mean for all the items in `my_2d_array`.

In [31]:
# Your implementation:
print("Mean of all items:", my_2d_array.mean())


Mean of all items: 52.0


**Action:** Calculate the mean for each column in `my_2d_array`.

In [32]:
# Your implementation:
print("Mean of each column:", my_2d_array.mean(axis=0))


Mean of each column: [48.66666667 53.66666667 50.66666667 49.33333333 54.33333333 52.33333333
 47.33333333 59.66666667]


**Action:** Calculate the mean for each row in `my_2d_array`.

In [33]:
# Your implementation:
print("Mean of each row:", my_2d_array.mean(axis=1))


Mean of each row: [50.25 50.25 55.5 ]


### Median

**Action:** Calculate the median for all items in `my_2d_array`.

In [34]:
# Your implementation:
print("Median of all items:", np.median(my_2d_array))



Median of all items: 51.0


**Action:** Calculate the median for each column in `my_2d_array`.

In [35]:
# Your implementation:
print("Median of each column:", np.median(my_2d_array, axis=0))


Median of each column: [48. 55. 51. 50. 53. 51. 45. 55.]


**Action:** Calculate the median for each row in `my_2d_array`.

In [36]:
# Your implementation:
print("Median of each row:", np.median(my_2d_array, axis=1))

Median of each row: [51.  49.5 52. ]


### Standard Deviation

**Action:** Calculate the standard deviation for all the items in `my_2d_array`.

In [37]:
# Your implementation:
print("Standard deviation of all items:", my_2d_array.std())


Standard deviation of all items: 6.59545297913646


**Action:** Calculate the standard deviation for each column in `my_2d_array`.

In [38]:
# Your implementation:
print("Standard deviation of each column:", my_2d_array.std(axis=0))


Standard deviation of each column: [ 0.94280904  2.62466929  1.24721913  2.49443826  2.62466929  4.98887652
  5.55777733 12.68419839]


**Action:** Calculate the standard deviation for each row in `my_2d_array`.

In [39]:
# Your implementation:
print("Standard deviation of each row:", my_2d_array.std(axis=1))


Standard deviation of each row: [4.17582327 4.40879802 8.67467579]


## Part H - Creating Arrays with Placeholder Data

**Action:** Create a 2-dimensionary array that has 4 rows and 5 columns, with all values as 0.  Then print the array.

In [41]:
# Your implementation:

zeros_array = np.zeros((4, 5))
print("Array with zeros:\n", zeros_array)


Array with zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Action:** Create a 2-dimensionary array that has 5 rows and 3 columns, filled with **ones (1s)** by using the `ones` function.  Then print the array.

In [42]:
# Your implementation:
ones_array = np.ones((5, 3))
print("Array with ones:\n", ones_array)



Array with ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Action:** Create a 2-dimensional array that has 5 rows and 3 columns, with all values as 1 (but make sure they are constrained to integers - you can use np.int64 or int).  Then print the array.

In [43]:
# Your implementation:
int_array = np.full((5, 3), 1, dtype=int)
print("Array with all values as 1:\n", int_array)


Array with all values as 1:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


**Action:** Create a 2-dimensional array that has 4 rows and 4 columns, with all values as 25 (constrained as integers).  Then print the array.

In [44]:
# Your implementation:

twenty_five_array = np.full((4, 4), 25, dtype=int)
print("Array with all values as 25:\n", twenty_five_array)


Array with all values as 25:
 [[25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]]


**Action:** Create a 2-dimensional array that has 3 rows and 5 columns, with each value being a random float from 0 to 1.  Then print the array.

In [45]:
# Your implementation:
random_array = np.random.rand(3, 5)
print("Array with random floats from 0 to 1:\n", random_array)


Array with random floats from 0 to 1:
 [[0.32624231 0.59007696 0.24137227 0.66292279 0.57935184]
 [0.7273332  0.97883542 0.88911639 0.73262604 0.16397431]
 [0.06690072 0.28224859 0.24661289 0.27789156 0.28047484]]


In [ ]:
# Thank You